config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :diaries
  get 'home/about'
  root 'diaries#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/diary.rb
class Diary < ApplicationRecord
    belongs_to :user

    def start_time
        self.created_at 
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :diaries
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
  before_action :set_diary, only: %i[show edit update destroy]
  before_action :correct_user, only: %i[edit destroy update]

  # GET /diaries or /diaries.json
  def index
    @diaries = Diary.all
  end

  # GET /diaries/1 or /diaries/1.json
  def show; end

  # GET /diaries/new
  def new
    @diary = current_user.diaries.build
  end

  # GET /diaries/1/edit
  def edit; end

  # POST /diaries or /diaries.json
  def create
    @diary = current_user.diaries.build(diary_params)

    respond_to do |format|
      if @diary.save
        format.html do
          redirect_to @diary, notice: 'Diary was successfully created.'
        end
        format.json { render :show, status: :created, location: @diary }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json do
          render json: @diary.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH/PUT /diaries/1 or /diaries/1.json
  def update
    respond_to do |format|
      if @diary.update(diary_params)
        format.html do
          redirect_to @diary, notice: 'Diary was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @diary }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json do
          render json: @diary.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /diaries/1 or /diaries/1.json
  def destroy
    @diary.destroy
    respond_to do |format|
      format.html do
        redirect_to diaries_url, notice: 'Diary was successfully deleted.'
      end
      format.json { head :no_content }
    end
  end

  def correct_user
    @diary = current_user.diaries.find_by(id: params[:id])
    if @diary.nil?
      redirect_to root_path, notice: 'You are not allowed to do it.'
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_diary
    @diary = Diary.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def diary_params
    params.require(:diary).permit(:title, :feeling, :text, :user_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/diaries/_form.html.erb
<%= form_with(model: diary) do |form| %>
  <% if diary.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(diary.errors.count, "error") %> prohibited this diary from being saved:</h2>

      <ul>
        <% diary.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <section>
  <div class="mask d-flex align-items-center h-100 gradient-custom-3">
    <div class="container h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-9 col-lg-7 col-xl-6">
          <div class="card" style="border-radius: 15px;">
            <div class="card-body p-5">
              <h2 class="text-center mb-5">New diary</h2>
                    <div class="field form-group">
                      <%= form.text_field :title, class:"form-control", placeholder:"Title" %>
                    </div>
                    <br>
                    <div class="field form-group">
                      <%= form.select :feeling, {'awsome': '🤩', 'good': '😊', 'not bad': '🙂', 'bad': '😞', 'awful': '😭'}, {include_blank: 'How do you feel today?'}, {class: 'form-control'}%>
                    </div>
                    <br>
                    <div class="field form-group">
                      <%= form.text_area :text, class:"form-control", placeholder:"Enter some text...", rows: "10" %>
                    </div>
                    <div class="field form-group">
                      <%= form.text_field :user_id, id: :diary_user_id, class:"form-control", value: current_user.id, type: :hidden %>
                    </div>
                    <br>
                    <div class="actions">
                      <%= form.submit class:"btn btn-dark", :style=>"background-color:#D15FEB; border-color:#D15FEB;" %>
                    </div>
                  <% end %>
                <br>
              <%= link_to 'Cancel', root_path, class:"btn btn-dark", :style=>"background-color:#7d7b7a; border-color:#7d7b7a;"  %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/diaries/edit.html.erb
<h1>Edit Diary</h1>

<%= render 'form', diary: @diary%>
<br>
<%= link_to ' Back', diaries_path, class:"btn btn-dark bi bi-house", :style=>"background-color:#D15FEB; border-color:#D15FEB;" %>

app/views/diaries/index.html.erb
<% if user_signed_in? %>
<h1>How do you feel today?</h1>
<br>
<%= link_to ' Add new diary', new_diary_path, class:"btn btn-dark bi bi-plus-circle-fill", :style=>"background-color:#D15FEB; border-color:#D15FEB;" %> 
<br>
<br>
<%= month_calendar(events: @diaries) do |date, diaries| %>
  <%= date.day %>
  <br>
  <% diaries.each do |diary| %>
    <%= link_to diary.feeling, diary, :style=>"text-decoration: none; font-size: 20px;"%>
<% end %>
<% end %>
<br>

<% else %>
<div class="head">
<h1>Welcome to Diary app!</h1>
<% end %>
</div>

app/views/diaries/new.html.erb
<%= render 'form', diary: @diary%>
<br>

app/views/diaries/show.html.erb
<div class="card">
  <h5 class="card-header"><%= @diary.created_at.localtime.strftime('%Y/%m/%d') %> <%= @diary.feeling %></h5>
  <div class="card-body">
    <h5 class="card-title">Title: <%= @diary.title %></h5>
    <p class="card-text"><%= @diary.text %></p>
    <%= link_to ' Edit', edit_diary_path(@diary), class:"btn btn-dark bi bi-pencil-square", :style=>"background-color:#D15FEB; border-color:#D15FEB;" %> 
    <%= link_to ' Delete', @diary, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-dark bi bi-trash", :style=>"background-color:#7d7b7a; border-color:#7d7b7a;"%>
  </div>
</div>
<br>
<%= link_to ' Back', root_path, class:"btn btn-dark bi bi-house" , :style=>"background-color:#D15FEB; border-color:#D15FEB;" %>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #D15FEB">
  <div class="container-fluid">
  <%= link_to ' Diary app', root_path, class:"navbar-brand bi bi-journals"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav"  style="color: #fff">
        <% if user_signed_in? %>
        <li class="nav-item">
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link"%>
        </li>
        <li class="nav-item">
            <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link"%>
        </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
            <%= link_to "Sign In", new_user_session_path, class:"nav-link"%>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About this app</h1>

app/views/home/index.html.erb
<h1>Diary app</h1>
This is my diary app!

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
   <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.0/font/bootstrap-icons.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@600&display=swap" rel="stylesheet">
    <title>My diary app</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <%= render 'home/header' %>
  <div class="container">
   </br>
    <% if notice%>
      <%= render 'layouts/alerts'%>
    <% end %>  
    <%= yield %>
  </div>  

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>